# Generated by Django 5.2.7 on 2025-10-20 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('stage_name', models.CharField(max_length=200, verbose_name='Nome Artístico')),
                ('real_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Real')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Links para redes sociais (Instagram, YouTube, etc.)', verbose_name='Links Sociais')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='Seguidores')),
                ('monthly_listeners', models.PositiveIntegerField(default=0, verbose_name='Ouvintes Mensais')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='genres.genre', verbose_name='Gênero Musical')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['-followers_count', '-created_at'],
            },
        ),
    ]
