# Generated by Django 5.2.7 on 2025-10-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil do artista', null=True, upload_to='artists/photos/', verbose_name='Foto do Artista'),
        ),
    ]
