# Generated by Django 5.2.7 on 2025-10-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='location',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='monthly_listeners',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='website',
        ),
    ]
