# Generated by Django 5.2.7 on 2025-10-20 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_artist_options_remove_artist_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Álbum')),
                ('cover', models.ImageField(blank=True, help_text='Capa do álbum', null=True, upload_to='albums/covers/', verbose_name='Capa do Álbum')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('featured', models.BooleanField(default=False, help_text='Álbum em destaque', verbose_name='Destaque')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artist', verbose_name='Artista')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbuns',
                'ordering': ['-featured', '-release_date', '-created_at'],
            },
        ),
    ]
