# Generated by Django 5.2.7 on 2025-10-18 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do banner', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descrição do banner', null=True, verbose_name='Descrição')),
                ('image', models.ImageField(help_text='Imagem do banner', upload_to='banners/', verbose_name='Imagem')),
                ('link_url', models.URLField(blank=True, help_text='URL para onde o banner deve redirecionar', null=True, verbose_name='URL de Destino')),
                ('banner_type', models.CharField(choices=[('home', 'Página Inicial'), ('artist', 'Página do Artista'), ('music', 'Página de Música'), ('playlist', 'Página de Playlist'), ('general', 'Geral')], default='general', help_text='Tipo de página onde o banner será exibido', max_length=20, verbose_name='Tipo de Banner')),
                ('position', models.CharField(choices=[('top', 'Topo'), ('middle', 'Meio'), ('bottom', 'Rodapé'), ('sidebar', 'Barra Lateral')], default='top', help_text='Posição onde o banner será exibido', max_length=20, verbose_name='Posição')),
                ('is_active', models.BooleanField(default=True, help_text='Se o banner está ativo e será exibido', verbose_name='Ativo')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora de início da exibição do banner', verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, help_text='Data e hora de fim da exibição do banner (opcional)', null=True, verbose_name='Data de Fim')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor número = maior prioridade)', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
