# Generated by Django 5.2.7 on 2025-10-18 12:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Imagem do banner', max_length=255, verbose_name='Imagem'),
        ),
    ]
