# Generated by Django 5.2.7 on 2025-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Imagem do banner', upload_to='banners/', verbose_name='Imagem'),
        ),
    ]
