services:
  db:
    image: postgres:15-alpine
    container_name: ehit_postgres
    environment:
      POSTGRES_DB: ehit_db
      POSTGRES_USER: ehit_user
      POSTGRES_PASSWORD: ehit_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ehit_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ehit_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - ehit_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  ehit_network:
    driver: bridge
