# Generated by Django 5.2.7 on 2025-10-20 01:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('album', models.CharField(blank=True, max_length=200, null=True, verbose_name='Álbum')),
                ('duration', models.PositiveIntegerField(help_text='Duração em segundos', verbose_name='Duração (segundos)')),
                ('file', models.FileField(help_text='Arquivo de áudio', upload_to='music/', verbose_name='Arquivo de Áudio')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Capa')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='Letra')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Lançamento')),
                ('streams_count', models.PositiveIntegerField(default=0, verbose_name='Reproduções')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Downloads')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Curtidas')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Em Destaque')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='artists.artist', verbose_name='Artista')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musics', to='genres.genre', verbose_name='Gênero Musical')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
                'ordering': ['-streams_count', '-created_at'],
            },
        ),
    ]
