# Generated by Django 5.2.7 on 2025-10-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, choices=[('', 'Selecione um gênero'), ('sertanejo', 'Sertanejo'), ('funk', 'Funk'), ('pop', 'Pop'), ('rock', 'Rock'), ('mpb', 'MPB'), ('forro', 'Forró'), ('pagode', 'Pagode'), ('samba', 'Samba'), ('axé', 'Axé'), ('reggae', 'Reggae'), ('rap', 'Rap/Hip Hop'), ('eletronica', 'Eletrônica'), ('gospel', 'Gospel'), ('blues', 'Blues'), ('jazz', 'Jazz'), ('classica', 'Clássica'), ('country', 'Country'), ('latin', 'Latina'), ('indie', 'Indie'), ('alternativa', 'Alternativa'), ('metal', 'Metal'), ('punk', 'Punk'), ('reggaeton', 'Reggaeton'), ('trap', 'Trap'), ('outros', 'Outros')], max_length=100, null=True, verbose_name='Gênero Musical'),
        ),
    ]
