# Generated by Django 5.2.7 on 2025-10-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hip-hop', 'Hip Hop'), ('rap', 'Rap'), ('r&b', 'R&B'), ('country', 'Country'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('dance', 'Dance'), ('reggae', 'Reggae'), ('funk', 'Funk'), ('soul', 'Soul'), ('gospel', 'Gospel'), ('latin', 'Latin'), ('world', 'World'), ('folk', 'Folk'), ('alternative', 'Alternative'), ('indie', 'Indie'), ('metal', 'Metal'), ('punk', 'Punk'), ('ska', 'Ska'), ('ambient', 'Ambient'), ('experimental', 'Experimental'), ('other', 'Other')], max_length=100, null=True, verbose_name='Gênero Musical'),
        ),
    ]
