# Generated by Django 5.2.7 on 2025-10-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duração em segundos (calculada automaticamente)', null=True, verbose_name='Duração (segundos)'),
        ),
    ]
