# Generated by Django 5.2.7 on 2025-10-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='lyrics',
        ),
    ]
