# Generated by Django 5.2.7 on 2025-10-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_initial'),
    ]

    operations = [
        # Primeiro, criar a nova tabela ManyToMany
        migrations.RunSQL(
            "CREATE TABLE playlists_playlist_musics (id INTEGER PRIMARY KEY AUTOINCREMENT, playlist_id INTEGER NOT NULL REFERENCES playlists_playlist(id) DEFERRABLE INITIALLY DEFERRED, music_id INTEGER NOT NULL REFERENCES music_music(id) DEFERRABLE INITIALLY DEFERRED);",
            reverse_sql="DROP TABLE playlists_playlist_musics;"
        ),
        
        # Copiar dados da tabela antiga para a nova
        migrations.RunSQL(
            "INSERT INTO playlists_playlist_musics (playlist_id, music_id) SELECT playlist_id, music_id FROM playlists_playlistmusic;",
            reverse_sql=""
        ),
        
        # Remover a tabela antiga
        migrations.RunSQL(
            "DROP TABLE playlists_playlistmusic;",
            reverse_sql="CREATE TABLE playlists_playlistmusic (id INTEGER PRIMARY KEY AUTOINCREMENT, playlist_id INTEGER NOT NULL REFERENCES playlists_playlist(id) DEFERRABLE INITIALLY DEFERRED, music_id INTEGER NOT NULL REFERENCES music_music(id) DEFERRABLE INITIALLY DEFERRED, added_at DATETIME NOT NULL, order INTEGER NOT NULL);"
        ),
        
        # Atualizar o campo no modelo
        migrations.AlterField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='music.music', verbose_name='Músicas'),
        ),
    ]
