# Generated by Django 5.2.7 on 2025-10-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_genre'),
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='music.music', verbose_name='Músicas'),
        ),
        migrations.DeleteModel(
            name='PlaylistMusic',
        ),
    ]
