# Generated by Django 5.2.7 on 2025-10-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'PlayHit', 'verbose_name_plural': 'PlayHits'},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
