# Generated by Django 5.2.7 on 2025-10-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_options_remove_playlist_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Se marcado, esta playlist aparecerá em destaque', verbose_name='Em Destaque'),
        ),
    ]
