# Generated by Django 5.2.7 on 2025-10-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_playlist_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['position', '-is_featured', '-created_at'], 'verbose_name': 'PlayHit', 'verbose_name_plural': 'PlayHits'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='position',
            field=models.CharField(choices=[('top', 'Topo'), ('middle', 'Meio'), ('bottom', 'Rodapé')], default='top', help_text='Posição onde a playlist será exibida', max_length=20, verbose_name='Posição'),
        ),
    ]
