# Generated by Django 5.2.7 on 2025-10-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_alter_playlist_options_playlist_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['order', '-is_featured', '-created_at'], 'verbose_name': 'PlayHit', 'verbose_name_plural': 'PlayHits'},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='position',
        ),
        migrations.AddField(
            model_name='playlist',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição no array (menor número = maior prioridade)', verbose_name='Ordem'),
        ),
    ]
