# apps/constants.py
# Constantes do sistema EHIT

GENRE_CHOICES = [
    ('pop', 'Pop'),
    ('rock', 'Rock'),
    ('hip-hop', 'Hip Hop'),
    ('rap', 'Rap'),
    ('r&b', 'R&B'),
    ('country', 'Country'),
    ('jazz', 'Jazz'),
    ('blues', 'Blues'),
    ('classical', 'Classical'),
    ('electronic', 'Electronic'),
    ('dance', 'Dance'),
    ('reggae', 'Reggae'),
    ('funk', 'Funk'),
    ('soul', 'Soul'),
    ('gospel', 'Gospel'),
    ('latin', 'Latin'),
    ('world', 'World'),
    ('folk', 'Folk'),
    ('alternative', 'Alternative'),
    ('indie', 'Indie'),
    ('metal', 'Metal'),
    ('punk', 'Punk'),
    ('ska', 'Ska'),
    ('ambient', 'Ambient'),
    ('experimental', 'Experimental'),
    ('other', 'Other'),
]
